Add PressureControl ROS server and client
iory/rcb4 pull request #69
Opened 2024-07-21 15:08 UTC by 708yamaguchi

# Usage

## keep pressure under -10[kPa]

Set `threshold` field as -10 and `release` field as false.

Shell
```
$ rostopic pub /kxr_fullbody_controller/pressure_control_interface/goal kxr_controller/PressureControlActionGoal "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
goal_id:
  stamp:
    secs: 0
    nsecs: 0
  id: ''
goal:
  board_idx: 39
  threshold: -10.0
  release: false" 
```

Python
```
roscd kxr_controller/scripts
python3 interface.py
In [1]: ri.send_pressure_control(39, threshold=-10, release=False)
```

Euslisp
```
roscd kxreus/euslisp
roseus kxr-interface.l
(kxr-init)
(send *ri* :send-pressure-control :board-idx 39 :threshold -10 :release nil)
```

## Connect to atmosphere

Set `release` field as true.

Shell
```
$ rostopic pub /kxr_fullbody_controller/pressure_control_interface/goal kxr_controller/PressureControlActionGoal "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
goal_id:
  stamp:
    secs: 0
    nsecs: 0
  id: ''
goal:
  board_idx: 39
  threshold: -10.0
  release: true" 
```

Python
```
roscd kxr_controller/scripts
python3 interface.py
In [1]: ri.send_pressure_control(39, threshold=-10, release=True)
```

Euslisp
```
roscd kxreus/euslisp
roseus kxr-interface.l
(kxr-init)
(send *ri* :send-pressure-control :board-idx 39 :threshold -10 :release t)
```

## Get current pressure

Shell
```
rostopic echo /kxr_fullbody_controller/pressure/39
data: 2.004485607147217
---                      
data: -0.006360102444887161
---                    
data: 0.9152774810791016
---                       
```

Python
```
roscd kxr_controller/scripts
python3 interface.py
In [1]: ri.read_pressure(39)
Out[1]: data: -16.13501739501953
```

Euslisp
```
roscd kxreus/euslisp
roseus kxr-interface.l
(kxr-init)
(send (send *ri* :read-pressure :board-idx 39) :data)
-11.8201
```

# elf files

See https://github.com/708yamaguchi/rcb4/releases/tag/v0.6.4.elf

2024-07-21 15:12 UTC, 708yamaguchi commented
This PR is extended version of https://github.com/iory/rcb4/pull/67.

2024-07-21 15:26 UTC, 708yamaguchi commented
TODO:

- How to decide board id.

```
    def search_air_board_ids(self):
        air_boards = self.all_air_boards()
        # TODO: How to decide (id*2) or (id*2+1)
        return np.array([air_board.id*2+1 for air_board in air_boards])
```

- Can we use raw board id (board_idx) in PressureControl.action? Should ROS system care about the board id?
```
uint16 board_idx  # Do not use board id? (Currently, bus-connected air board is not supported)
```

2024-07-21 17:35 UTC, nakane11 commented
Regarding `search_air_board_ids()`, what about filtering `self.id_vector` using `j.board_revision` as is done in  `all_air_boards()`?
Maybe self.id_vector needs to be updated with  `read_jointbase_sensor_ids()`

2024-07-21 19:20 UTC, 708yamaguchi commented
@nakane11 
Thank you for your review.
Does the last commit match your idea?

2024-07-21 23:09 UTC, nakane11 commented
@708yamaguchi 
Thank you, that's exactly right.

2024-08-16 13:53 UTC, iory requested changes

2024-08-16 13:53 UTC, iory commented on ros/kxreus/euslisp/kxr-interface.l
> +   (dolist (action (list servo-on-off-client stretch-client pressure-control-client))
The pressure-control-client is not supported on the rcb4 board, so it is better not to check it.

2024-08-16 15:25 UTC, merged

2024-08-16 15:25 UTC, iory commented
LGTM