Publish average pressure and use it in pressure control loop
iory/rcb4 pull request #75
Opened 2024-08-22 14:24 UTC by 708yamaguchi

Use average pressure (denoised value) for rostopic publisher and pressure control loop.

Blue line: raw pressure
Red line: average pressure (20 pressure average)

![Screenshot from 2024-08-22 23-21-39](https://github.com/user-attachments/assets/805d78ff-5bba-4d42-96ef-3b0319c7ddbb)

2024-08-22 14:55 UTC, iory requested changes

2024-08-22 14:55 UTC, iory commented on ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
> +                self.recent_pressures = deque([], maxlen=1*hz)
int(hz) is better

2024-08-22 14:59 UTC, 708yamaguchi commented on ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
> +                self.recent_pressures = deque([], maxlen=1*hz)
Thank you, I updated.

2024-08-23 03:46 UTC, iory approved these changes

2024-08-23 03:47 UTC, merged